name: CI Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Executes Tests
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Tests with Maven
      run: mvn -B test --file pom.xml
